ALTER TABLE resorts ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS website_url TEXT;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS cover_image_url TEXT;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS description_md TEXT;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS region_id TEXT;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS department TEXT;

ALTER TABLE resorts ADD COLUMN IF NOT EXISTS altitude_base_m INTEGER;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS altitude_top_m INTEGER;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS altitude_min_m INTEGER;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS altitude_max_m INTEGER;

ALTER TABLE resorts ADD COLUMN IF NOT EXISTS season_open_date DATE;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS season_close_date DATE;

ALTER TABLE resorts ADD COLUMN IF NOT EXISTS ski_area_km INTEGER;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS lifts_count INTEGER;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS pistes_count INTEGER;
ALTER TABLE resorts ADD COLUMN IF NOT EXISTS amenities TEXT;
